### ISSUE TITLE
looking for cljs pretty printer

### ISSUE THREAD

**Issue by borkdude** [shaunlebron/cljs-pprint#1]
Hello Shaun,

I was looking around for a pretty printer that I could use from a browser REPL. 
Since the development of this repo is halted, what do you recommend using now?

**Comment by shaunlebron** [comment]
Hi, there are no pretty-printers available for cljs yet.  I am actually resuming development here after a discussion on Jira with David.

A lighter weight pretty-printer, fipp, has a cljs port being tracked [here](https://github.com/brandonbloom/fipp/issues/7).  That one will probably be finished before mine if they can find someone to do it.
