### ISSUE TITLE
Better is-whitespace? check

### ISSUE THREAD

**Issue by bostonou** [shaunlebron/cljs-pprint#19]
[`is-whitespace?`](https://github.com/shaunlebron/cljs-pprint/blob/master/src/cljs/cljs/pprint.cljs#L2064-L2096) is less complete than the [Java `Character/isWhitespace` used in clj](https://github.com/shaunlebron/cljs-pprint/blob/master/src/clj/pprint/cl_format.clj#L1151).

**Comment by swannodette** [comment]
Use `goog.string.isSpace`
