### ISSUE TITLE
Better is-letter? check

### ISSUE THREAD

**Issue by bostonou** [shaunlebron/cljs-pprint#20]
[`is-letter?`](https://github.com/shaunlebron/cljs-pprint/blob/master/src/cljs/cljs/pprint.cljs#L1959-L1964) is less complete than the [Java `Character/isLetter` used in clj](https://github.com/shaunlebron/cljs-pprint/blob/master/src/clj/pprint/cl_format.clj#L1113).

**Comment by swannodette** [comment]
Use `goog.string.isUnicodeChar`
