### ISSUE TITLE
Is cljs-pprint usable yet?

### ISSUE THREAD

**Issue by casidiablo** [shaunlebron/cljs-pprint#8]
So from what I understand, this repo is just a way for you to show your progress on porting pprint to cljs, right? Does that mean that it's actually not usable yet? I can't seem to find a way to import this library into my project... would it work if I try to copy the cljs source code into it? Or is the port just too far from actually doing something?

**Comment by shaunlebron** [comment]
It's not usable at the moment.  It will be merged into clojurescript core when done though.  This is just a repo to help me and others wrap our heads around the problem and to map out what's left to do.

**Comment by casidiablo** [comment]
Thanks for the clarification. Keep it up dude!
